In [4]:
import gseapy as gp
from gseapy import Biomart
import pandas as pd
import matplotlib.pyplot as plt
import os
import glob

In [5]:
bm = Biomart()
marts = bm.get_marts()
print(marts)
datasets = bm.get_datasets(mart='ENSEMBL_MART_ENSEMBL')

                    Mart                    Version
0   ENSEMBL_MART_ENSEMBL           ensembl_mart_108
1     ENSEMBL_MART_MOUSE             mouse_mart_108
2  ENSEMBL_MART_SEQUENCE          sequence_mart_108
3  ENSEMBL_MART_ONTOLOGY          ontology_mart_108
4   ENSEMBL_MART_GENOMIC  genomic_features_mart_108
5       ENSEMBL_MART_SNP               snp_mart_108
6   ENSEMBL_MART_FUNCGEN        regulation_mart_108

In [6]:
datasets

,Dataset,Description
0,abrachyrhynchus_gene_ensembl,Pink-footed goose genes (ASM259213v1)
1,pkingsleyae_gene_ensembl,Paramormyrops kingsleyae genes (PKINGS_0.1)
2,nscutatus_gene_ensembl,Mainland tiger snake genes (TS10Xv2-PRI)
3,clumpus_gene_ensembl,Lumpfish genes (fCycLum1.pri)
4,llaticaudata_gene_ensembl,Blue-ringed sea krait genes (latLat_1.0)
...,...,...
210,ssberkshire_gene_ensembl,Pig - Berkshire genes (Berkshire_pig_v1)
211,ecalabaricus_gene_ensembl,Reedfish genes (fErpCal1.1)
212,pnattereri_gene_ensembl,Red-bellied piranha genes (Pygocentrus_nattere...
213,neugenii_gene_ensembl,Wallaby genes (Meug_1.0)
214,acitrinellus_gene_ensembl,Midas cichlid genes (Midas_v5)

In [7]:
attrs = bm.get_attributes(dataset='hsapiens_gene_ensembl')
attrs

,Attribute,Description,Additional
0,ensembl_gene_id,Gene stable ID,Stable ID of the Gene
1,ensembl_gene_id_version,Gene stable ID version,Versionned stable ID of the Gene
2,ensembl_transcript_id,Transcript stable ID,Stable ID of the Transcript
3,ensembl_transcript_id_version,Transcript stable ID version,Versionned stable ID of the Transcript
4,ensembl_peptide_id,Protein stable ID,
...,...,...,...
3157,cdna_coding_start,cDNA coding start,
3158,cdna_coding_end,cDNA coding end,
3159,genomic_coding_start,Genomic coding start,
3160,genomic_coding_end,Genomic coding end,
3161,is_constitutive,Constitutive exon,

In [18]:
gene_names = pd.read_csv("genes.tsv", sep = '\t')
len(gene_names['gene'].values.astype(str).tolist())

164

In [17]:
queries ={'external_gene_name': gene_names['gene'].values.astype(str).tolist()}
results = bm.query(dataset='hsapiens_gene_ensembl',
                   attributes=['external_gene_name', 'entrezgene_id'],
                   filters=queries)
results.to_csv('enterz_id.tsv', sep = '\t', index = True)